name: Build ImmortalWrt

on:
  push:
    branches:
      - master
    paths:
      - '.config'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget

      - name: Clone source
        run: |
          git clone --depth 1 https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          git clone --depth 1 https://github.com/kenzok8/openwrt-packages.git package/kenzok8
          git clone --depth 1 https://github.com/kenzok8/small.git package/small
          cp ../.config .config

      - name: Build firmware
        run: |
          cd immortalwrt
          make defconfig
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: immortalwrt-x86_64
          path: immortalwrt/bin/targets/x86/64/
