name: Build OpenWrt (LEDE)

on:
  # 仅手动触发，防止误触发。等我们配完 .config 再改成 push 触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget python3

      - name: Clone LEDE source
        run: |
          git clone https://github.com/coolsnowwolf/lede
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          # 如果仓库里已有 .config 就复制进去；若没有也不报错（我们稍后会添加）
          if [ -f ../.config ]; then cp ../.config ./.config; fi

      - name: Compile firmware
        run: |
          cd lede
          make defconfig
          # 并行编译，失败则降级为单线程输出详细日志
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-firmware
          path: lede/bin/targets/
